name: Containers build and push

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      context-path:
        required: true
        type: string
      compose-path:
        required: true
        type: string
      registry:
        required: true
        string: true

env:
  REGISTRY: ${{ inputs.registry }}

jobs:
  containers_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Get PIP dependencies
      - name: Cache PIP
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python${{env.PYTHON_VER}}
          key: ${{ runner.os }}-pip

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        working-directory: ${{ inputs.working-directory }}
        run: |
          git clone https://github.com/INGInious/util-compose.git
          pip3 install -r util-compose/requirements.txt

      - name: Generate compose file
        working-directory: ${{ inputs.working-directory }}/util-compose
        run: python3 generate.py ${{ inputs.context-path}} ${{ inputs.compose-path }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push containers
        working-directory: ${{ inputs.working-directory }}
        run: |
          # see https://github.com/docker/buildx/issues/344#issuecomment-846626613
          docker buildx create --use
          echo "FROM scratch" | docker buildx build -
          docker compose build --push
