name: Containers build and push

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      context-path:
        required: true
        type: string
      compose-path:
        required: true
        type: string
      registry:
        required: true
        type: string
      container_type:
        required: true
        type: string
      version:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

env:
  REGISTRY: ${{ inputs.registry }}
  TYPE: ${{ inputs.container_type }}

jobs:
  containers_build_and_push:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: |
          git clone https://github.com/INGInious/util-compose.git
          pip3 install -r util-compose/requirements.txt

      - name: Generate compose file
        working-directory: ${{ inputs.working-directory }}/util-compose
        run: python3 generate.py ../${{ inputs.context-path}} ../${{ inputs.compose-path }} ${{ inputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push containers
        working-directory: ${{ inputs.working-directory }}
        run: |
          # see https://github.com/docker/buildx/issues/344#issuecomment-846626613
          docker buildx create --use
          echo "FROM scratch" | docker buildx build -
          docker compose build --push
          docker compose push
